### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by samhstn** [zwilias/elm-html-string#1]
You could instead look to use: http://package.elm-lang.org/packages/evancz/elm-graphics/1.0.1/Element#toHtml

**Comment by zwilias** [comment]
Hm, I'm not sure I understand the suggestion. Could you elaborate how that would allow one to write out something that looks like regular `elm-lang/html` and decide later whether it should be rendered as virtual-dom or as a `String`?

**Comment by samhstn** [comment]
Sorry, ignore me. Great library, thanks for making it, will be using it in the future.
I saw the use of `toHtml` in some source code and assumed that it did a similar thing, but I was totally off.
