### ISSUE TITLE
Elm 0.19 migration

### ISSUE THREAD

**Issue by azuken** [zwilias/elm-html-string#3]
Hi,

We are using since a year your library, and it works well. (Thank you)

Since Elm 0.19 is out, we waited all our dependencies to be up to date for migration. I checked again today for all our dependencies, and it seems elm-html-string is the only left to be migrated.

I've already forked your project and make migration, you can see it here :

https://github.com/azuken/elm-html-string

My problem is with `Event` attribute type, which use `onWithOptions`, removed in Elm 0.19. You must use `Html.Events.custom `now.

This method accept two parameters (event name, and decoder with message and options), instead of three (name, options, and msg decoder). I tried to figured out the error, but I'm stuck with `map` functions (`mapAttributes` & `mapChildren`). Can you please check it, and if you are able to, tell me how to fit it ?

I am creating a pull request for easier readability.

Thank you in advance !

Azuken

**Comment by azuken** [comment]
I tried to remove `Event` part, to see if there is more adaptation for Elm 0.19, and when I updated `String.elm` module with new `elm/html` module, I had another warning for `Elm.Kernel.VirtualDom`, reserved for internal use. I pushed it anyway.

**Comment by zwilias** [comment]
An 0.19 upgrade has since been released!
